export const GET_COMMENT_PENDING = 'GET_COMMENT_PENDING'
export const GET_COMMENT_SUCCESS = 'GET_COMMENT_SUCCESS'
export const GET_COMMENT_FAIL = 'GET_COMMENT_FAIL'

export const POST_COMMENT_PENDING = 'POST_COMMENT_PENDING'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_FAIL = 'POST_COMMENT_FAIL'