export const GET_FILES_PENDING = 'GET_FILES_PENDING'
export const GET_FILES_SUCCESS = 'GET_FILES_SUCCESS'
export const GET_FILES_FAIL = 'GET_FILES_FAIL'

export const ADD_FILE_PENDING = 'ADD_FILE_PENDING'
export const ADD_FILE_SUCCESS = 'ADD_FILE_SUCCESS'
export const ADD_FILE_FAIL = 'ADD_FILE_FAIL'
