export const ADD_FRIEND_PENDING = 'ADD_FRIEND_PENDING'
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS'
export const ADD_FRIEND_FAIL = 'ADD_FRIEND_FAIL'

export const ACCEPT_FRIEND_PENDING = 'ACCEPT_FRIEND_PENDING'
export const ACCEPT_FRIEND_SUCCESS = 'ACCEPT_FRIEND_SUCCESS'
export const ACCEPT_FRIEND_FAIL = 'ACCEPT_FRIEND_FAIL'