export const GET_POSTS_PENDING = 'GET_POSTS_PENDING'
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS'
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL'

export const GET_POST_DETAILS_PENDING = 'GET_POST_DETAILS_PENDING'
export const GET_POST_DETAILS_SUCCESS = 'GET_POST_DETAILS_SUCCESS'
export const GET_POST_DETAILS_FAIL = 'GET_POST_DETAILS_FAIL'

export const ADD_POST_PENDING = 'ADD_POST_PENDING'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'
